site_name: Kusi's Knowledgebase
site_description: 'Knowledgebase'
site_author: 'Markus König'

nav:
  - Home: index.md
  - Azure: 
    - VMs: Azure/VMs/index.md
  - M365: 
    - PnP: M365/PnP/index.md
    - SPFx:
      - Tips: M365/SPFx/index.md
      - Word Add-In: M365/SPFx/wordaddin.md
    - PowerShell: M365/PowerShell/index.md
    - ichicraft: M365/ichicraft/index.md
  - OnPrem: 
    - SharePoint: onPrem/SP/index.md
    - PnP: onPrem/PnP/index.md
    - SPFx:
      - Tips: onPrem/SPFx/index.md
      - Utils: onPrem/SPFx/utils.md
      - SPFxCam: onPrem/SPFx/spfxCam.md
      - MegaMenu: onPrem/SPFx/megaMenu.md
      - Manual:
        - Introduction: onPrem/SPFx/intro.md
        - Development environment: onPrem/SPFx/devenv.md
        - Create a new Project: onPrem/SPFx/createProject.md
        - Project structure: onPrem/SPFx/projectStructure.md
        - Migrate SPFx 2016 to 2019: onPrem/SPFx/migrate16to19.md
    - PowerShell: onPrem/PowerShell/index.md
  - PowerPlatform: 
    - PowerPlatform: PowerPlatform/index.md
    - PowerFx: PowerPlatform/PowerFx/index.md
    - Flow: PowerPlatform/Flow/index.md
    - Center of Excellence: PowerPlatform/CoE/index.md
  - React: 
    - React: React/index.md
  - About: 
    - About: About/index.md
    - Links: About/links.md

theme:
  name: 'material'
  language: 'en'
  logo: 'assets/sharepoint.png'
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky    
    - navigation.path
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: 'Copyright &copy; 2023 Markus König'

repo_url: https://github.com/kusi1975/spkb
edit_uri: blob/master/docs/